# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('comment', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
