# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoilr_contact', '0001_initial'),
        ('spoilr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoilr_core.team'),
        ),
    ]
