name: Set up Django's manage.py
description: Set up Python environment for using Django's manage.py

inputs:
  requirements_file:
    description: Which requirements file to use for pip (relative to the requirements sub-directory)
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: 'requirements/**'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/${{ inputs.requirements_file }}
      shell: bash
