# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New request'), ('approved', 'Approved request'), ('cancelled', 'Cancelled request'), ('withdrawn', 'Withdrew request')], default='new', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('submission', 'Submission for puzzle'), ('story', 'Story'), ('unlock', 'Unlock'), ('answer', 'Answer')], max_length=64)),
                ('invite_template', models.TextField(blank=True, null=True)),
                ('message_template', models.TextField(blank=True, null=True)),
                ('puzzle_trigger_solved', models.BooleanField(blank=True, null=True)),
                ('email_key_trigger', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_order', models.IntegerField(blank=True, null=True)),
                ('round_solve_count_to_unlock', models.IntegerField(blank=True, null=True)),
                ('hints_force_released', models.BooleanField(default=False)),
                ('hints_release_delay', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Puzzle data',
                'verbose_name_plural': 'Puzzle data',
            },
        ),
        migrations.CreateModel(
            name='RoundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Round data',
                'verbose_name_plural': 'Round data',
            },
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=128)),
                ('missing_documents', models.BooleanField(default=False)),
                ('extra_puzzle_radius', models.SmallIntegerField(default=0)),
                ('act2_puzzle_radius_increased', models.BooleanField(default=False)),
                ('radius_increased_1', models.BooleanField(default=False)),
                ('act3_release', models.BooleanField(default=False)),
                ('act3_release_emailed', models.BooleanField(default=False)),
                ('act3_release_1', models.BooleanField(default=False)),
                ('act3_release_1_emailed', models.BooleanField(default=False)),
                ('act3_release_2', models.BooleanField(default=False)),
                ('act3_release_2_emailed', models.BooleanField(default=False)),
                ('act3_release_3_emailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Team data',
                'verbose_name_plural': 'Team data',
            },
        ),
        migrations.CreateModel(
            name='TeamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
