# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(max_length=500)),
                ('recipient', models.CharField(max_length=500)),
                ('received_time', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_time'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('body_text', models.TextField()),
                ('sender', models.CharField(max_length=500)),
                ('recipient', models.CharField(max_length=500)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('automated', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_time'],
            },
        ),
    ]
