# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoilr_email', '0001_initial'),
        ('spoilr_hq', '0001_initial'),
        ('spoilr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoilr_hq.handler'),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoilr_core.interaction'),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spoilr_email.incomingmessage'),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoilr_core.team'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoilr_core.interaction'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoilr_core.team'),
        ),
    ]
