# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoilr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionAccessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied', models.BooleanField(default=False)),
                ('interaction_access', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spoilr_core.interactionaccess')),
            ],
        ),
    ]
