# Generated by Django 3.2.8 on 2022-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('team_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Team E-mail')),
                ('team_emoji', models.CharField(blank=True, help_text='This will be displayed publicly to all other teams.', max_length=50, null=True, verbose_name='Team Emoji')),
                ('captain_pronouns', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pronouns')),
                ('captain_phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('bg_bio', models.CharField(default='', help_text='This will be displayed publicly to all other teams.', max_length=1500, verbose_name='Team Bio')),
                ('bg_style', models.CharField(choices=[('fun', 'We’re playing for fun!'), ('compete', 'We’re pretty into puzzles but we’re not so focused on winning.'), ('win', 'We hope to see the entire hunt and maybe find the coin.')], default='fun', max_length=20, verbose_name='What describes your team’s style of playing?')),
                ('bg_win', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Teams are strongly encouraged to have active MIT students on their team because Mystery Hunt is an MIT event. At least 2 MIT students are required to write the hunt.', max_length=20, verbose_name='Is your team hoping to win the hunt?')),
                ('bg_first_year', models.CharField(default='', max_length=200, verbose_name='In which year was your team members’ earliest experience of the MIT Mystery Hunt?')),
                ('bg_started', models.CharField(default='', max_length=200, verbose_name='When was your team established?')),
                ('bg_location', models.CharField(default='', max_length=200, verbose_name='Where are your team members located?')),
                ('bg_comm', models.CharField(default='', max_length=200, verbose_name='What communication application will you be using to communicate with your team members while solving the MIT Mystery Hunt this year?')),
                ('size_total', models.IntegerField(default=0, verbose_name='How many people are on your team in total?')),
                ('size_last_year', models.IntegerField(default=0, verbose_name='How many people were on your team last year?')),
                ('size_undergrads', models.IntegerField(default=0, verbose_name='How many MIT undergraduates?')),
                ('size_grads', models.IntegerField(default=0, verbose_name='How many MIT graduate students?')),
                ('size_alumni', models.IntegerField(default=0, verbose_name='How many MIT alumni?')),
                ('size_faculty', models.IntegerField(default=0, verbose_name='How many members from MIT faculty and staff?')),
                ('size_minors', models.IntegerField(default=0, verbose_name='How many minors (under 18 during Hunt)?')),
                ('other_unattached', models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=20, verbose_name='Are you willing to enlist unattached solvers?')),
                ('other_workshop', models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=20, verbose_name='Would your team like to participate in the How to Hunt workshop prior to the event?')),
                ('other_puzzle_club', models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=20, verbose_name='Do you have members from the MIT Puzzle Club on your team?')),
                ('other_how', models.CharField(choices=[('', ''), ('past', 'We’ve played in the past'), ('group', 'Through a puzzle interest group (e.g. National Puzzlers’ League)'), ('word-of-mouth', 'Word of mouth from past participants or organizers'), ('social', 'Through e-mail or social media'), ('puzzle-club', 'Through the MIT Puzzle Club'), ('other', 'Other')], default='', max_length=20, verbose_name='How did you hear about the MIT Mystery Hunt?')),
                ('other', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Anything else you’d like to share with us? Comments, questions, puns?')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnattachedSolverRegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First (Given) Name or Nickname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('pronouns', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pronouns')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('bg_mitmh', models.CharField(default='', max_length=1500, verbose_name='Have you participated in the MIT Mystery Hunt before? If so, tell us about your Hunt history!')),
                ('bg_puzzles', models.CharField(default='', max_length=1500, verbose_name='Have you played in other puzzle-type events before? If so, feel free to give a short summary.')),
                ('bg_style', models.CharField(choices=[('win', 'I’m a puzzle machine and I’d love to be on a team that wants to find the coin. I really want to see the whole hunt.'), ('compete', 'I’m pretty into puzzles, but not so focused on winning'), ('fun', 'I’m just playing for fun, and would like to make some new friends.')], default='fun', max_length=20, verbose_name='What describes your style of playing?')),
                ('bg_prefs', models.CharField(default='', max_length=500, verbose_name='Do you have any other preferences about what team you want to join? Would you prefer a bigger or smaller team? Team of current students or of alumni and older players?')),
                ('bg_age', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, verbose_name='Are you under 18?')),
                ('bg_mit', models.CharField(default='', max_length=500, verbose_name='Are you connected to the MIT community? (If so, how?)')),
                ('other', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Anything else you’d like to share with us? Comments, questions, puns?')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
