name: 'Prod: Deploy puzzle files'

on: workflow_dispatch

concurrency:
  group: deploy-puzzle-files-prod
  cancel-in-progress: true

jobs:
  deploy:
    uses: 'Palindrome-Puzzles/2022-hunt/.github/workflows/deploy-puzzle-files.yml@main'
    with:
      django_env: 'prod_deploy'
      gzip_files: true
      gcloud_bucket: mitmh2022
    secrets:
      GCLOUD_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATIONS_CREDENTIAL }}
      GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
